### ISSUE TITLE
I get my base64encodedstring ,but it contain a line break 

### ISSUE THREAD

**Issue by NeoHu** [l4u/NSData-Base64#5]
NSString *dataBaseString = [[@"qwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiop" dataUsingEncoding:NSASCIIStringEncoding] base64EncodedString];

log:
dataBaseString :cXdlcnR5dWlvcHF3ZXJ0eXVpb3Bxd2VydHl1aW9wcXdlcnR5dWlvcHF3ZXJ0eXVp
b3A= 

i think it happens because the length of the origin string.

**Comment by l4u** [comment]
Please use the new iOS 7 API . or try https://github.com/nicklockwood/Base64 for iOS version < 7
